[book]
authors = ["d41y"]
title = "Cybersecurity Notes"
language = "en"
src = "src" 

[preprocessor.callouts]

[preprocessor.pagetoc]

[output.html]
git-repository-url = "https://github.com/d41y/d41y.github.io"
#git-repository-icon = "fa-github"
#additional-css = ["theme/pagetoc.css"]
#additional-js = ["theme/pagetoc.js"]
additional-css = ["theme/custom.css"]

[output.html.fold]
enable = true
level = 1
