[book]
authors = ["d41y"]
title = "Cybersecurity Notes"
language = "en"
src = "src"

# added
[preprocessor.callouts]

[preprocessor.wikilinks]

[preprocessor.wikilinks.options]
extension = ".md"
pretty-links = false
use-link-labels = true

[output.html.fold]
enable = true
level = 1
