[book]
authors = ["d41y"]
title = "Cybersecurity Notes"
language = "en"
src = "src"

# added
[preprocessor.embedify]
footer.enable = true
footer.message = "2025 • Created by [d41y](https://github.com/d41y)"

[preprocessor.callouts]

[preprocessor.wikilinks]

[preprocessor.wikilinks.options]
extension = ".md"
pretty-links = false
use-link-labels = true

[output.html.fold]
enable = true
level = 1

[output.html.print]
enable = false

[output.html]
git-repository-url = "https://github.com/d41y/d41y.github.io"
git-repository-icon = "fa-github"
